export const GET_SECTIONS = 'GET_SECTIONS';
export const GET_SECTIONS_SUCCESS = 'GET_SECTIONS_SUCCESS';
export const GET_SECTIONS_FAIL = 'GET_SECTIONS_FAIL';

export const GET_SECTION = 'GET_SECTION';
export const GET_SECTION_SUCCESS = 'GET_SECTION_SUCCESS';
export const GET_SECTION_FAIL = 'GET_SECTION_FAIL';

export const DELETE_SECTION = 'DELETE_SECTION';
export const DELETE_SECTION_SUCCESS = 'DELETE_SECTION_SUCCESS';
export const DELETE_SECTION_FAIL = 'DELETE_SECTION_FAIL';

export const ADD_SECTION = 'ADD_SECTION';
export const ADD_SECTION_SUCCESS = 'ADD_SECTION_SUCCESS';
export const ADD_SECTION_FAIL = 'ADD_SECTION_FAIL';

export const UPDATE_SECTION = 'UPDATE_SECTION';
export const UPDATE_SECTION_SUCCESS = 'UPDATE_SECTION_SUCCESS';
export const UPDATE_SECTION_FAIL = 'UPDATE_SECTION_FAIL';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
